---
version: "3.7"
volumes:
  shared-workspace:
    name: "workspace"
    driver: local

services:
  python:
    image: ${SANDBOX_ID}.dkr.ecr.eu-west-2.amazonaws.com/results-cicd:spp-engine
    volumes:
      - shared-workspace:/opt/workspace
      - .:/usr/src/app
    environment:
      JAVA_HOME: /usr/lib/jvm/java-8-openjdk-amd64
      PYSPARK_PYTHON: python3
      PYSPARK_SUBMIT_ARGS: "pyspark-shell"
    depends_on:
      - spark
    command: pytest
  spark:
    container_name: spark
    image: ${SANDBOX_ID}.dkr.ecr.eu-west-2.amazonaws.com/results-cicd:sparkimg
    volumes:
      - shared-workspace:/opt/workspace
      - .:/usr/src/app
    environment:
      JAVA_HOME: /usr/local/openjdk-8/bin/java
      SPARK_HOME: /opt/workspace/spark-2.4.6-bin-hadoop2.7
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET}

working_dir: /usr/src/app
